blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', cache_page(60)(ArticleListView.as_view()), name='list'),
    path('view/<int:pk>', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('publish/<int:pk>', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('client/', include('client.urls', namespace='client'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import contact, MailingListView, MailingDetailView, MailingCreateView, \
    MailingUpdateView, MailingDeleteView, main


app_name = MailingConfig.name

urlpatterns = [
    #path('', MailingListView.as_view(), name='list'),
    path('', main, name='main'),
    path('contact/', contact, name='contact'),
    #path('main/', main, name='main'),
    path('list/', MailingListView.as_view(), name='list'),
    path('view/<int:pk>', MailingDetailView.as_view(), name='view_mailing'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('edit/<int:pk>', MailingUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MailingDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import now

NULLABLE = {
    'blank': True,
    'null': True
}


class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое статьи')
    img = models.ImageField(verbose_name='изображение', **NULLABLE)
    count_views = models.IntegerField(default=0, verbose_name='количество просмотров', **NULLABLE)
    date_published = models.DateTimeField(default=now, verbose_name='дата публикации', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано', **NULLABLE)
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

mailing/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):

    theme = models.CharField(max_length=150, verbose_name='тема сообщения')
    body = models.TextField()

    def __str__(self):
        return f"{self.theme}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):

    TITLE_CHOICES_PERIODICITY = [
        (1, 'Раз в день'),
        (2, 'Раз в неделю',),
        (3, 'Раз в месяц',),
    ]

    TITLE_CHOICES_STATUS = [
        (1, 'Создана'),
        (2, 'Запущена',),
        (3, 'Завершена',),
    ]

    mailing_time = models.DateTimeField(verbose_name="время рассылки", default=timezone.now)
    periodicity = models.PositiveSmallIntegerField(verbose_name="периодичность", choices=TITLE_CHOICES_PERIODICITY, default=1)
    status = models.PositiveSmallIntegerField(verbose_name='статус рассылки', choices=TITLE_CHOICES_STATUS, default=1)
    massage = models.ForeignKey(Message, on_delete=models.SET_NULL, **NULLABLE)
    user = models.ForeignKey(User, verbose_name='пользователь', on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f"{self.status}"

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'


class Log(models.Model):

    date_attempt = models.DateTimeField(verbose_name='Дата попытки')
    status = models.CharField(max_length=150, verbose_name='Статус попытки')
    answer = models.TextField(**NULLABLE, verbose_name='ответ сервера')
    mailing = models.ForeignKey(Mailing, **NULLABLE, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.status} {self.date_attempt}"

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms

from mailing.models import Mailing


class MailingForms(forms.ModelForm):

    class Meta:
        model = Mailing
        fields = '__all__'

mailing/views.py
from datetime import datetime

import smtplib
import pytz
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.mail import send_mail

from blog.models import Article
from client.models import Client
from mailing.forms import MailingForms
from mailing.models import Mailing, Log


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            key = f'log_list_{self.object.pk}'
            log_list = cache.get(key)
            if log_list is None:
                log_list = self.object.log_set.all()
                cache.set(key, log_list)
        else:
            log_list = self.object.log_set.all()
        context_data['logs'] = log_list

        return context_data


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name} {email} {message}')
    context = {
        'title': "Контакты"
    }
    return render(request, 'mailing/contact.html', context)


def main(request):
    clients = len(Client.objects.all().distinct('email'))
    article = Article.objects.filter(is_published=True).order_by('?')
    mailing = len(Mailing.objects.all())
    mailing_active = len(Mailing.objects.filter(status=2))
    context = {
        'title': "Главная",
        'article': article[:3],
        'mailing': mailing,
        'mailing_active': mailing_active,
        'clients': clients
    }
    return render(request, 'mailing/main.html', context)


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForms
    permission_required = 'mailing.add_mailing'
    success_url = reverse_lazy('mailing:list')

    def form_valid(self, form):
        tz = pytz.timezone('Europe/Moscow')
        clients = [client.email for client in Client.objects.filter(user=self.request.user)]
        new_mailing = form.save()

        if new_mailing.mailing_time <= datetime.now(tz):
            mail_subject = new_mailing.massage.body if new_mailing.massage is not None else 'Рассылка'
            message = new_mailing.massage.theme if new_mailing.massage is not None else 'Вам назначена рассылка'
            try:
                send_mail(mail_subject, message, settings.EMAIL_HOST_USER, clients)
                log = Log.objects.create(date_attempt=datetime.now(tz), status='Успешно', answer='200', mailing=new_mailing)
                log.save()
            except smtplib.SMTPDataError as err:
                log = Log.objects.create(date_attempt=datetime.now(tz), status='Ошибка', answer=err, mailing=new_mailing)
                log.save()
                #raise err
            except smtplib.SMTPException as err:
                log = Log.objects.create(date_attempt=datetime.now(tz), status='Ошибка', answer=err, mailing=new_mailing)
                log.save()
                #raise err
            except Exception as err:
                log = Log.objects.create(date_attempt=datetime.now(tz), status='Ошибка', answer=err, mailing=new_mailing)
                log.save()
                #raise err
            new_mailing.status = 3
            if new_mailing.user is None:
                new_mailing.user = self.request.user
            new_mailing.save()

        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForms
    permission_required = 'mailing.change_mailing'
    success_url = reverse_lazy('mailing:list')


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Mailing
    permission_required = 'mailing.delete_mailing'
    success_url = reverse_lazy('mailing:list')

mailing/templates/mailing/contact.html
{% extends 'mailing/base.html'%}
{% block content%}
<div class="col-md-6">
    <div class="card">
        <div class="card-body">
            <p class="card-text">
                Офис Москва
            </p>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card">
        <div class="card-body">
            <h2>Напишите нам</h2>
            <form method="post">
                {% csrf_token %}
                <input class="form-control m-2" name="name">
                <input class="form-control m-2" name="email">
                <textarea class="form-control m-2" name="message"></textarea>
                <button type="submit" class="m-2 btn btn-primary form-control">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock%}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html'%}
{% block content %}

<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.mailing_time }}</p>
            <p class="card-text">{{ object.get_periodicity_display }}</p>
            <p class="card-text">
                {% if object.status == 3 %}
                    <span class="text-muted">{{ object.get_status_display }}</span>
                {% else %}
                    {{ object.get_status_display }}
                {% endif %}
            </p>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <div class="card-title">
                Отчет по отправке
            </div>
        </div>
        <div class="card-body">
            {% for log in logs %}
            <p class="card-text">{{ log.date_attempt }} {{ log.status }} {{ log.answer }}</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление рассылки
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:create'%}">Добавить рассылку</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.mailing_time }}</p>
            <p class="card-text">{{ object.get_periodicity_display }}</p>
            <p class="card-text">
                {% if object.status == 3 %}
                    <span class="text-muted">{{ object.get_status_display }}</span>
                {% else %}
                    {{ object.get_status_display }}
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.mailing.view_mailing %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'mailing:view_mailing' object.pk %}">View</a></button>
                    {% endif %}
                    {% if perms.mailing.change_mailing %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'mailing:edit' object.pk %}">Edit</a></button>
                    {% endif %}
                    {% if perms.mailing.delete_mailing %}
                        <button type="button" class="btn btn-sm btn-outline-danger"><a href="{% url 'mailing:delete' object.pk %}">Delete</a></button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/main.html
{% extends 'mailing/base.html'%}
{% block content %}
<p>Количество рассылок: {{ mailing }}</p>
<p>Количество активных рассылок: {{ mailing_active }}</p>
<p>Количество уникальных клиентов для рассылок: {{ clients }}</p>
{% for object in article %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.title }}</p>
            <p class="card-text">
                {% if object.is_published %}
                    <span class="text-muted">Опубликовано</span>
                {% else %}
                    <span class="text-muted">Не опубликовано</span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.blog.view_article %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'blog:view' object.pk %}">View</a></button>
                    {% endif %}
                    {% if perms.blog.change_article %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'blog:edit' object.pk %}">Edit</a></button>
                    {% endif %}
                    {% if perms.blog.delete_article%}
                        <button type="button" class="btn btn-sm btn-outline-danger"><a href="{% url 'blog:delete' object.pk %}">Delete</a></button>
                    {% endif %}
                </div>
                <small class="text-body-secondary">Просмотров: {{ object.count_views }}</small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}