blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', cache_page(60)(ArticleListView.as_view()), name='list'),
    path('view/<int:pk>', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('publish/<int:pk>', toggle_activity, name='toggle_activity'),
]

client/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import DeleteView

from client.apps import ClientConfig
from client.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView

app_name = ClientConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('edit/<int:pk>', ClientUpdateView.as_view(), name='edit'),
    path('view/<int:pk>', ClientDetailView.as_view(), name='view_client'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('client/', include('client.urls', namespace='client'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

client/models.py
from django.db import models

from mailing.models import Mailing
from users.models import User

NULLABLE = {
    'blank': True,
    'null': True
}


class Client(models.Model):
    """Класс для описания клиента"""

    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    second_name = models.CharField(max_length=100, verbose_name='отчество')
    email = models.EmailField()
    comment = models.TextField(**NULLABLE)
    user = models.ForeignKey(User, verbose_name='пользователь', on_delete=models.CASCADE, **NULLABLE)

    is_active = models.BooleanField(default=True, **NULLABLE)
    #mailing = models.ForeignKey(Mailing, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Рассылка')

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.second_name}"

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

client/forms.py
from django import forms

from client.models import Client


class ClientForms(forms.ModelForm):

    class Meta:
        model = Client
        fields = '__all__'

client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from client.forms import ClientForms
from client.models import Client


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'client/client_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ClientDetailView(DetailView):
    model = Client
    template_name = 'client/client_detail.html'


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForms
    success_url = reverse_lazy('client:list')

    def form_valid(self, form):
        new_client = form.save()
        if new_client.user is None:
            new_client.user = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForms
    success_url = reverse_lazy('client:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('client:list')

client/templates/client/client_confirm_delete.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пользователя?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'client:list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

client/templates/client/client_detail.html
{% extends 'mailing/base.html'%}
{% block content %}

<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object }}</p>
            <p class="card-text">{{ object.email }}</p>
            <p class="card-text">{{ object.comment }}</p>
            {% if object.is_active %}
                <p class="card-text">Активен</p>
            {% else %}
                <p class="card-text">Не активен</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

client/templates/client/client_form.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление клиента
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

client/templates/client/client_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'client:create'%}">Добавить клиента</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object }}</p>
            <p class="card-text">{{ object.email }}</p>
            <p class="card-text">{{ object.comment }}</p>
            {% if object.is_active %}
                <p class="card-text">Активен</p>
            {% else %}
                <p class="card-text">Не активен</p>
            {% endif %}

            <p class="card-text">
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.client.view_client %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'client:view_client' object.pk %}">View</a></button>
                    {% endif %}
                    {% if perms.client.change_client %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'client:edit' object.pk %}">Edit</a></button>
                    {% endif %}
                    {% if perms.client.delete_client %}
                        <button type="button" class="btn btn-sm btn-outline-danger"><a href="{% url 'client:delete' object.pk %}">Delete</a></button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}