blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', cache_page(60)(ArticleListView.as_view()), name='list'),
    path('view/<int:pk>', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('publish/<int:pk>', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('client/', include('client.urls', namespace='client'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import now

NULLABLE = {
    'blank': True,
    'null': True
}


class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое статьи')
    img = models.ImageField(verbose_name='изображение', **NULLABLE)
    count_views = models.IntegerField(default=0, verbose_name='количество просмотров', **NULLABLE)
    date_published = models.DateTimeField(default=now, verbose_name='дата публикации', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано', **NULLABLE)
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/forms.py
from django import forms

from blog.models import Article

class ArticleForms(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

    def clean_title(self):
        arr_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        # cleaned_data = self.cleaned_data[fields]
        for item in arr_words:
            cleaned_data = self.cleaned_data['title']
            if item in cleaned_data:
                raise forms.ValidationError('Ошибка загрузки запрещенных продуктов!')
        return cleaned_data

    def clean_content(self):

        arr_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        # cleaned_data = self.cleaned_data[fields]
        for item in arr_words:
            cleaned_data = self.cleaned_data['content']
            if item in cleaned_data:
                raise forms.ValidationError('Ошибка загрузки запрещенных продуктов!')
        return cleaned_data

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import ArticleForms
from blog.models import Article


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForms
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_art = form.save()
            new_art.slug = slugify(new_art.title)
            new_art.save()

        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForms
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_art = form.save()
            new_art.slug = slugify(new_art.title)
            new_art.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('blog:list')


@login_required
def toggle_activity(request, pk):
    article_item = get_object_or_404(Article, pk=pk)
    if article_item.is_published:
        article_item.is_published = False
    else:
        article_item.is_published = True
    article_item.save()

    return redirect(reverse('blog:list'))

blog/templates/blog/article_confirm_delete.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить статью {{ object.title }}?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing_service:list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'mailing/base.html' %}
{% load my_tag %}
{% block content %}
<div class="col-12">
    <div class="card mb-3">
        <div class="card-body">
            <img src="{{ object.img|mediapath }}" class="card-img-top" alt="..."/>
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{object.content| title}}</p>
            <p class="card-text">{{ object.description }}</p>

            {% if object.is_published %}
                <a class="btn btn-warning" href="{% url 'blog:toggle_activity' object.pk %}">Опубликовать</a>
            {% else %}
                <a class="btn btn-success" href="{% url 'blog:toggle_activity' object.pk %}">Опубликовать</a>
            {% endif %}
        </div>
        <div class="card-footer text-muted ">
          <div class="float-start">
          <p class="card-text">Дата создания: {{ object.data_create }}</p>
          </div>
          <div class="float-md-end">
            <p class="card-text ">Просмотры: {{ object.count_views }}</p>
          </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create'%}">Добавить статью</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">{{ object.title }}</p>
            <p class="card-text">
                {% if object.is_published %}
                    <span class="text-muted">Опубликовано</span>
                {% else %}
                    <span class="text-muted">Не опубликовано</span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.blog.view_article %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'blog:view' object.pk %}">View</a></button>
                    {% endif %}
                    {% if perms.blog.change_article %}
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'blog:edit' object.pk %}">Edit</a></button>
                    {% endif %}
                    {% if perms.blog.delete_article%}
                        <button type="button" class="btn btn-sm btn-outline-danger"><a href="{% url 'blog:delete' object.pk %}">Delete</a></button>
                    {% endif %}
                </div>
                <small class="text-body-secondary">Просмотров: {{ object.count_views }}</small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}